"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const cleanup = __importStar(require("./commands/cleanup"));
exports.cleanup = cleanup;
const install = __importStar(require("./commands/install"));
exports.install = install;
const list = __importStar(require("./commands/list"));
exports.list = list;
const set = __importStar(require("./commands/set"));
exports.set = set;
const uninstall = __importStar(require("./commands/uninstall"));
exports.uninstall = uninstall;
var utils_1 = require("./universal/utils");
exports.convertTimes = utils_1.convertTimes;
